### ISSUE TITLE
MFC Erroneous Readouts

### ISSUE THREAD

**Issue by jdshutter** [nthallen/keutsch-PlantHub#4]
Even when no gas cylinder is connected to the MFCs, the MFCs still readout a flow.

For instance, the zero MFC setpoint was set to 0 sccm, but the MFC was reading out a range from 630-660 sccm. Similarly, the CO2 MFC setpoint was set to 2 sccm, but the MFC was reading out ranges from 2.2 - 2.9 sccm. 

Also, we're sometimes see ****** as the readout flow, but this might just be a formatting issue?

**Comment by nthallen** [comment]
Can you verify the voltage on the flow sense line when you are testing this? As you note, the flow should be zero with no cylinder attached, so what is the voltage that the flow controller is reporting? Is it steady?

Also, let's double-check the data sheet for the flow controller to see if we have the correct conversion. The conversion I'm using is for 0-5 V, but some flow controllers have 1-5V outputs.

**Comment by jdshutter** [comment]
Yes, the output signal is from 0-5 V, so it's the correct conversion.

**Comment by jdshutter** [comment]
Noticed that even if the setpoint is explicitly set to 2 V (not sccm) on the Zero MFC that the voltage reading for the setpoint using the ladder (with no MFC connected) was -0.1 V.

**Comment by jdshutter** [comment]
According to Marco, Vref on the FCC DAQ should read 2.5 V if enabled and 0 V if disabled. We read 0 V when connected to analog ground which could mean that it's either not enabled by the microcontroller or the DAQ could be a dud.

**Comment by jdshutter** [comment]
The correct setpoints for the MFCs are now being sent after pressing the RESET button, but the MFCs are not actually adjusting to go to the setpoints.

**Comment by jdshutter** [comment]
Issue was discovered with the +/- 15 V power supply that was only outputting +/- 13.86 V. Using an external power supply at +/- 15 V worked perfectly.
